"""add rolename

Revision ID: abb36f45a422
Revises: 
Create Date: 2024-03-07 10:35:44.735809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import alembic_postgresql_enum


# revision identifiers, used by Alembic.
revision: str = 'abb36f45a422'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('role', postgresql.ENUM('USER', 'STAFF', 'ADMIN', name='role_enum',
                                                      create_type=False), nullable=False),
                    sa.Column('salary', sa.Integer(), nullable=True),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    sa.Enum('USER', 'STAFF', 'ADMIN', name='role_enum').drop(op.get_bind())
    # ### end Alembic commands ###
