"""add datatime

Revision ID: 19b371dcfa65
Revises: b1986efd9491
Create Date: 2024-03-13 16:46:28.561665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b371dcfa65'
down_revision: Union[str, None] = 'b1986efd9491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('solution', sa.Column('responsed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'responsed_at')
    op.drop_column('request', 'created_at')
    # ### end Alembic commands ###
