"""updated solution

Revision ID: 8b8a606f6313
Revises: 8bc0702d56bf
Create Date: 2024-03-16 20:15:18.690341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8b8a606f6313'
down_revision: Union[str, None] = '8bc0702d56bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('request', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.add_column('solution', sa.Column('username', sa.String(length=30), nullable=False))
    op.alter_column('solution', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solution', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('solution', 'username')
    op.alter_column('request', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('request', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
