"""add datatime/correct_response

Revision ID: be5765047825
Revises: 19b371dcfa65
Create Date: 2024-03-13 16:47:45.706615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be5765047825'
down_revision: Union[str, None] = '19b371dcfa65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('response_at', sa.DateTime(), nullable=True))
    op.drop_column('solution', 'responsed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('responsed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('solution', 'response_at')
    # ### end Alembic commands ###
